# Site settings
title: 陈达的博客
header-img: img/home-bg.jpg
email: cendar@126.com
copyright_name: chenda.me 所有文章转载请注明来源 
description: "一个80后程序猿的技术博客，记录一些有的没的想法。"
keywords: "技术,程序猿,程序员,博客,陈达的博客,原创"
baseurl: ""
url: "http://chenda.me"
twitter_username: SBootstrap
github_username:  davidtmiller
facebook_username:  IronSummitMedia
email_username:  cendar@126.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
